export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const FETCH_PRODUCT_SAGA = "FETCH_PRODUCT_SAGA";
export const ADD_PRODUCT_SAGA = "ADD_PRODUCT_SAGA";
export const DELETE_PRODUCT_SAGA = "DELETE_PRODUCT_SAGA";
export const UPDATE_PRODUCT_SAGA = "UPDATE_PRODUCT_SAGA";

export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
